### ISSUE TITLE
incorrect sex

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [afsc-assessments/sampler#14]
https://github.com/afsc-assessments/sampler/blob/843eb3ca0091d6d4e6ad3331297bdb59b2fb55bc/R/QueryAgesForSampler.R#L64

@careymcgilliard it looks like all of these functions are incorrectly assigning sex, there are `F, M, U` sexes so `U` is being assigned as males for all these functions - unless I'm misreading something?

**Comment by careymcg** [comment]
@BenWilliams-NOAA  Fixed this bug to assigned unsexed fish to SEXNO = 3.

QueryLengthsForSampler.r:
```r
Length.df<-Length.df %>% mutate(SEXNO=case_when(SEX=="F" ~ 1,SEX == 'M' ~ 2,SEX == 'U' ~ 3))
```
QueryAgesForSampler.r:
```r
AgeLength.df<-AgeLength.df %>% mutate(SEXNO=case_when(SEX=="F" ~ 1,SEX == 'M' ~ 2,SEX == 'U' ~ 3), AGE=ifelse(is.na(AGE),-9,AGE)) %>%

```
