### ISSUE TITLE
How to initiate bootstrapping?

### ISSUE THREAD

**Issue by Cole-Monnahan-NOAA** [afsc-assessments/sampler#9]
@jimianelli-NOAA I may be misunderstanding something but it appears the flag to do bootstrapping doesn't work

````
 !! ad_comm::change_datafile_name("bs_setup.dat");
  init_int nbs;
  !! if (nbs==0||do_sim) nbs=1;
````

So if `do_sim==1` this will essentially disable bootstrapping. `do_sim` is set to 1 if the flag `-sim` is detected, which seems backward, shouldn't it be

````
  !! if (nbs==0 || !do_sim) nbs=1;
````

Also `do_sim` is uninitialized so probably good to add `do_sim=0` as you do for `do_check` [here](https://github.com/afsc-assessments/sampler/blob/main/src/sam.tpl#L12).

I tried modifying the code and now when I add `-sim` it does bootstrapping and when not then it won't. I can do a PR if this is desired behavior.

**Comment by jimianelli** [comment]
Agree do_sim should have been initialized. Can mess up number of bootstraps otherwise.

**Comment by Cole-Monnahan-NOAA** [comment]
Fixed in this commit: https://github.com/afsc-assessments/sampler/commit/843eb3ca0091d6d4e6ad3331297bdb59b2fb55bc

Note that `do_sim` is related to an documented simulation feature, not bootstrapping.
